imports:
  - { resource: Backend/DashboardWidgets.yaml }
services:
  # general settings
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  CodingFreaks\CfCookiemanager\:
    resource: '../Classes/*'

  # dependency injection (override public setting)
  CodingFreaks\CfCookiemanager\Controller\CookieSettingsBackendController:
    public: true
    tags: [ 'backend.controller' ]

  CodingFreaks\CfCookiemanager\Service\AutoconfigurationService:
    public: true

  CodingFreaks\CfCookiemanager\Service\ThumbnailService:
    public: true

  CodingFreaks\CfCookiemanager\Utility\RenderUtility:
    autowire: true
    public: true
    arguments:
      $eventDispatcher: '@Psr\EventDispatcher\EventDispatcherInterface'

  CodingFreaks\CfCookiemanager\EventListener\AddIntroJsModule:
    tags:
      - name: event.listener
        event: TYPO3\CMS\Backend\Controller\Event\BeforeFormEnginePageInitializedEvent

  CodingFreaks\CfCookiemanager\Controller\BackendAjax\UpdateCheckController:
    public: true
    arguments:
      $responseFactory: '@Psr\Http\Message\ResponseFactoryInterface'

  CodingFreaks\CfCookiemanager\Controller\BackendAjax\InstallController:
    public: true